burger_meat/burger_meat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('menu.urls')),
    path('account/',include('account.urls')),
    path('', include('social_django.urls')),
    path('cart/',include('cart.urls')),
    path('order/',include('orders.urls')),
    # path('', include('django.contrib.flatpages.urls')),#!

]
if settings.DEBUG:
    # import debug_toolbar
    #
    # urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

burger_meat/cart/urls.py
from django.urls import path
from .views import cart_add,cart_detail,cart_remove

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/',cart_add,name='cart_add'),
    path('detail/',cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',cart_remove,name='cart_remove'),

]

burger_meat/orders/urls.py
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
    path('',order_create,name='order'),
    path('to_complete/',to_complete,name='to_complete'),
]

burger_meat/cart/models.py
from django.db import models

# Create your models here.

burger_meat/cart/forms.py
from django import forms



class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(max_value=20)
    update = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

burger_meat/cart/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .cart import Cart
from django.views.decorators.http import require_POST
from menu.models import Menu
from .forms import CartAddProductForm



@require_POST
def cart_add(request,product_id):
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        product = get_object_or_404(Menu,id=product_id)
        cd = form.cleaned_data
        cart = Cart(request)
        cart.add(
            product=product,
            quantity=cd['quantity'],
            update_quantity=cd['update']
        )
        if cd['update']:
            return redirect('cart:cart_detail')
    return redirect('menu')

def cart_detail(request):
    cart = Cart(request)

    return render(request,'cart/detail.html',{'cart':cart})

def cart_remove(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Menu,id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

burger_meat/cart/templates/cart/detail.html
 {% extends 'base.html' %}
 {% load static %}
 {% block content %}
     <section class="section-cart">
            <div class="container container-cart">
                <h2 class="title cart-title">Корзина</h2>
                <table class="cart">
                    <tbody>
                        {% for item in cart %}
                            <tr>
                                <td class="item-cart"><img class="burger-img"src="{{ item.product.photo.url }}" alt=""></td>
                                <td class="item-cart"><h3>{{ item.product.name }}</h3></td>
                                <td class="item-cart">
                                    <form class="win-buy-cart" action="{% url 'cart:cart_add' item.product.id %}" method="post">
                                        <div class="minus">-</div>
                                        <input class="input_count" name="quantity" type="text" value="{{ item.quantity }}">
                                        <input type="hidden" name="update" value="True">
                                        <div class="plus">+</div>
                                        <input class="to-basket to-basket-edit cart-edit" type="submit" value="Изменить">
                                        {% csrf_token %}
                                    </form>
                                </td>
                                <td class="item-cart">{{ item.total_price }} руб.</td>
                                <td class="item-cart ">
                                    <a class="to-basket to-basket-edit cart-edit" href="{% url 'cart:cart_remove' item.product.id %}">
                                        Удалить
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <p class="cart-text-right">
                    <a class="reset-login" href="{% url 'menu' %}#menu" class="button light">Вернуться в меню</a>
                    {% if cart|length > 0 %}
                    <a class="reset-login" href="{% url 'orders:order' %}" class="button">Оформить</a>
                    {% endif %}
                </p>
             <script src="{% static 'js/buy_modal.js' %}"></script>
            </div>
     </section>
 {% endblock %}